import type { Metadata } from "next";
import "./globals.css";
import "material-symbols";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400..900&family=Dancing+Script:wght@400..700&family=Explora&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />

         <meta property="og:title" content="Invitación" />
          <meta property="og:description" content="¡Te invito a mi baby shower!" />
          <meta property="og:image" content="https://invitagil.com/preview.png" />
          <meta property="og:url" content="https://invitagil.com/" />
          <meta property="og:type" content="website" />
      </head>
      <body>
        {children}

        <ToastContainer />
      </body>
    </html>
  );
}
