import type { Metadata } from "next";
import "./globals.css";
import "material-symbols";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateMetadata({
  searchParams,
}: {
  searchParams: { g?: string };
}): Promise<Metadata> {
  const g = searchParams.g || "";

  const url = `https://invitagil.com/invitations?g=${g}`;

  return {
    title: "Invitación",
    description: "¡Te invito a mi evento!",
    openGraph: {
      title: "Invitación",
      description: "¡Te invito a mi evento!",
      url,
      type: "website",
      images: [
        {
          url: "https://invitagil.com/preview.png",
          width: 1200,
          height: 630,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      images: ["https://invitagil.com/preview.png"],
    },
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400..900&family=Dancing+Script:wght@400..700&family=Explora&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {children}

        <ToastContainer />
      </body>
    </html>
  );
}
